#!/usr/bin/env bash

rm -f ~/.config/tmux/tmux.conf
ln -s ~/Documents/diegovr/projects/dotfiles/tmux/tmux.conf ~/.config/tmux/tmux.conf

# Install xclip beforehand
#
rm -rf ~/.config/tmux/plugins/
# mkdir -p ~/.config/tmux/plugins/
#
# # Install TPM
# if [ ! -f ~/.config/tmux/plugins/tpm/tpm ]; then
#     echo "installing TPM"
#     git clone https://github.com/tmux-plugins/tpm ~/.config/tmux/plugins/tpm
# fi
